# Classification Challenge

Wine experts can identify wines from specific vineyards through smell and taste, but the factors that give different wines their individual charateristics are actually based on their chemical composition.

In this challenge, you must train a classification model to analyze the chemical and visual features of wine samples and classify them based on their cultivar (grape variety).

> **Citation**: The data used in this exercise was originally collected by Forina, M. et al.
>
> PARVUS - An Extendible Package for Data Exploration, Classification and Correlation.
Institute of Pharmaceutical and Food Analysis and Technologies, Via Brigata Salerno,
16147 Genoa, Italy.
>
> It can be downloaded from the UCI dataset repository (Dua, D. and Graff, C. (2019). [UCI Machine Learning Repository]([http://archive.ics.uci.edu/ml). Irvine, CA: University of California, School of Information and Computer Science).

## Explore the data

Run the following cell to load a CSV file of wine data, which consists of 12 numeric features and a classification label with the following classes:

- **0** (*variety A*)
- **1** (*variety B*)
- **2** (*variety C*)

In [15]:
import pandas as pd

# load the training dataset
data = pd.read_csv('data/wine.csv')
data.sample(10)

,Alcohol,Malic_acid,Ash,Alcalinity,Magnesium,Phenols,Flavanoids,Nonflavanoids,Proanthocyanins,Color_intensity,Hue,OD280_315_of_diluted_wines,Proline,WineVariety
93,12.29,2.83,2.22,18.0,88,2.45,2.25,0.25,1.99,2.15,1.15,3.30,290,1
81,12.72,1.81,2.20,18.8,86,2.20,2.53,0.26,1.77,3.90,1.16,3.14,714,1
161,13.69,3.26,2.54,20.0,107,1.83,0.56,0.50,0.80,5.88,0.96,1.82,680,2
51,13.83,1.65,2.60,17.2,94,2.45,2.99,0.22,2.29,5.60,1.24,3.37,1265,0
75,11.66,1.88,1.92,16.0,97,1.61,1.57,0.34,1.15,3.80,1.23,2.14,428,1
5,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450,0
80,12.00,0.92,2.00,19.0,86,2.42,2.26,0.30,1.43,2.50,1.38,3.12,278,1
82,12.08,1.13,2.51,24.0,78,2.00,1.58,0.40,1.40,2.20,1.31,2.72,630,1
72,13.49,1.66,2.24,24.0,87,1.88,1.84,0.27,1.03,3.74,0.98,2.78,472,1
54,13.74,1.67,2.25,16.4,118,2.60,2.90,0.21,1.62,5.85,0.92,3.20,1060,0

Your challenge is to explore the data and train a classification model that achieves an overall *Recall* metric of over 0.95 (95%).

> **Note**: There is no single "correct" solution. A sample solution is provided in [03 - Wine Classification Solution.ipynb](03%20-%20Wine%20Classification%20Solution.ipynb).

## Train and evaluate a model

Add markdown and code cells as required to to explore the data, train a model, and evaluate the model's predictive performance.

In [ ]:
# Your code to evaluate data, and train and evaluate a classification model

## Use the model with new data observation

When you're happy with your model's predictive performance, save it and then use it to predict classes for the following two new wine samples:

- \[13.72,1.43,2.5,16.7,108,3.4,3.67,0.19,2.04,6.8,0.89,2.87,1285\]
- \[12.37,0.94,1.36,10.6,88,1.98,0.57,0.28,0.42,1.95,1.05,1.82,520\]

In [ ]:
# Your code to predict classes for the two new samples

### Prep batch for inferencing

In [6]:
# code from AML Studio > Datasets > WineDataForInferencing > Consume
from azureml.core import Workspace, Dataset

subscription_id = 'dca8aaf5-3be9-45c1-a5ec-bdbd92f56b11'
resource_group = 'sewald101_ds_study'
workspace_name = 'ds_sandbox'

workspace = Workspace(subscription_id, resource_group, workspace_name)

dataset = Dataset.get_by_name(workspace, name='WineDataForInferencing')
dataset.download(target_path='../data/wine_dataset/', overwrite=False)

['/mnt/batch/tasks/shared/LS_root/mounts/clusters/ds-study-ds11v2/code/Users/ml-basics/data/wine_dataset/_meta.yaml',
 '/mnt/batch/tasks/shared/LS_root/mounts/clusters/ds-study-ds11v2/code/Users/ml-basics/data/wine_dataset/_samples.json',
 '/mnt/batch/tasks/shared/LS_root/mounts/clusters/ds-study-ds11v2/code/Users/ml-basics/data/wine_dataset/data.dataset',
 '/mnt/batch/tasks/shared/LS_root/mounts/clusters/ds-study-ds11v2/code/Users/ml-basics/data/wine_dataset/data.dataset.parquet',
 '/mnt/batch/tasks/shared/LS_root/mounts/clusters/ds-study-ds11v2/code/Users/ml-basics/data/wine_dataset/data.visualization',
 '/mnt/batch/tasks/shared/LS_root/mounts/clusters/ds-study-ds11v2/code/Users/ml-basics/data/wine_dataset/schema/_schema.json']

In [13]:
!ls ../data/wine_dataset/

_meta.yaml     data.dataset	     data.visualization
_samples.json  data.dataset.parquet  schema

In [16]:
p_path = '../data/wine_dataset/data.dataset.parquet'
df1 = pd.read_parquet(p_path)
df1.head()

,Alcohol,Malic_acid,Ash,Alcalinity,Magnesium,Phenols,Flavanoids,Nonflavanoids,Proanthocyanins,Color_intensity,Hue,OD280_315_of_diluted_wines,Proline,WineVariety
0,12.42,1.61,2.19,22.5,108,2.00,2.09,0.34,1.61,2.06,1.060,2.96,345,1
1,14.22,3.99,2.51,13.2,128,3.00,3.04,0.20,2.08,5.10,0.890,3.53,760,0
2,13.05,2.05,3.22,25.0,124,2.63,2.68,0.47,1.92,3.58,1.130,3.20,830,0
3,11.64,2.06,2.46,21.6,84,1.95,1.69,0.48,1.35,2.80,1.000,2.75,680,1
4,12.29,1.61,2.21,20.4,103,1.10,1.02,0.37,1.46,3.05,0.906,1.82,870,1

In [20]:
feature_cols = df1.columns[:-1]
target_col = df1.columns[-1]

df_to_inference = df1[feature_cols]
df_actuals = df1[target_col]